"""QCore public Python API.

QCore is the product brand. ``qplanck`` is the importable Python package.
"""

from qplanck import gates, pulse, qir
from qplanck.backends import LocalSimulator, MockBackend
from qplanck.circuit import Circuit
from qplanck.compiler import (
    CompilationTrace,
    CompiledCircuit,
    CompileOptions,
    DependencyGraph,
    ResourceMetrics,
)
from qplanck.compiler import (
    compile as compile_circuit,
)
from qplanck.errors import (
    CircuitError,
    InteropError,
    NativeCompilerError,
    QASMError,
    QPlanckError,
    ResourceLimitError,
    RoutingError,
    TargetError,
    UnsupportedOperationError,
)
from qplanck.ibm import IBM_TARGET_METADATA_SCHEMA_VERSION, target_from_ibm_backend
from qplanck.interop import ConversionResult, InteropIssue, InteropIssueKind, LossReport
from qplanck.ir import CircuitIR, MeasurementSpec, Operation, Parameter
from qplanck.planning import (
    CandidateDisposition,
    CandidatePlan,
    CompilerStrategy,
    Manifest,
    MetricConstraint,
    Objective,
    Plan,
    PlanExplanation,
    PlanMetrics,
    PlanningError,
    PlanningManifest,
    Program,
    QCoreNativeStrategy,
    StrategyError,
    StrategyResult,
    StrategyTimeoutError,
    StrategyUnavailableError,
    StrategyUnsupportedError,
    plan,
)
from qplanck.qir import (
    QIRCapabilities,
    QIRExportError,
    QIRManifest,
    QIRModule,
    QIRProfile,
    export_qir,
    export_qir_with_report,
)
from qplanck.qiskit_strategy import (
    QISKIT_STRATEGY_VERSION,
    QiskitCompilerStrategy,
    QiskitStrategy,
    qiskit_strategies,
)
from qplanck.replay import ReplayError, ReplayMismatch, ReplayReport, replay
from qplanck.results import ExecutionTrace, ProbabilityResult, RunResult, StatevectorResult
from qplanck.routing import RoutingStep, RoutingTrace, RoutingTrial
from qplanck.runtime import (
    Backend,
    BackendError,
    CalibratedCircuit,
    Diagnostic,
    ExecutionOptions,
    ExperimentManifest,
    ExternalArtifactRef,
    Job,
    JobCancelledError,
    JobError,
    JobFailedError,
    JobStatus,
    JobTimeoutError,
)
from qplanck.simulator import Simulator
from qplanck.targets import (
    InstructionSupport,
    Layout,
    LimitKind,
    Target,
    TargetLimit,
    TargetLimits,
    Topology,
)

__all__ = [
    "Backend",
    "BackendError",
    "CalibratedCircuit",
    "CandidateDisposition",
    "CandidatePlan",
    "Circuit",
    "CircuitError",
    "CircuitIR",
    "CompilationTrace",
    "CompiledCircuit",
    "CompilerStrategy",
    "CompileOptions",
    "ConversionResult",
    "DependencyGraph",
    "Diagnostic",
    "ExecutionOptions",
    "ExperimentManifest",
    "ExecutionTrace",
    "ExternalArtifactRef",
    "InteropError",
    "InteropIssue",
    "InteropIssueKind",
    "IBM_TARGET_METADATA_SCHEMA_VERSION",
    "InstructionSupport",
    "Job",
    "JobCancelledError",
    "JobError",
    "JobFailedError",
    "JobStatus",
    "JobTimeoutError",
    "LocalSimulator",
    "Layout",
    "LimitKind",
    "LossReport",
    "Manifest",
    "MeasurementSpec",
    "MetricConstraint",
    "MockBackend",
    "NativeCompilerError",
    "Objective",
    "Operation",
    "Parameter",
    "Plan",
    "PlanExplanation",
    "PlanMetrics",
    "PlanningError",
    "PlanningManifest",
    "ProbabilityResult",
    "Program",
    "QASMError",
    "QISKIT_STRATEGY_VERSION",
    "QCoreNativeStrategy",
    "QIRCapabilities",
    "QIRExportError",
    "QIRManifest",
    "QIRModule",
    "QIRProfile",
    "QiskitCompilerStrategy",
    "QiskitStrategy",
    "QPlanckError",
    "ResourceLimitError",
    "ResourceMetrics",
    "ReplayError",
    "ReplayMismatch",
    "ReplayReport",
    "RoutingError",
    "RoutingStep",
    "RoutingTrace",
    "RoutingTrial",
    "RunResult",
    "Simulator",
    "StatevectorResult",
    "StrategyError",
    "StrategyResult",
    "StrategyTimeoutError",
    "StrategyUnavailableError",
    "StrategyUnsupportedError",
    "Target",
    "TargetError",
    "TargetLimit",
    "TargetLimits",
    "Topology",
    "UnsupportedOperationError",
    "compile_circuit",
    "export_qir",
    "export_qir_with_report",
    "gates",
    "plan",
    "pulse",
    "qir",
    "qiskit_strategies",
    "replay",
    "target_from_ibm_backend",
]

__version__ = "0.3.0a1"
